services:
  - type: web
    name: video2text-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LOCAL_FOLDER
        value: .
      - key: OUTPUT_DIR
        value: ./transcripts
      - key: WHISPER_MODEL
        value: tiny
      - key: LANGUAGE
        value: vi
      - key: ALLOWED_ORIGINS
        sync: false
      - key: MAX_UPLOAD_SIZE
        value: "524288000"
    plan: free
