services:
  - type: web
    name: subtitle-generation
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: LOCAL_FOLDER
        value: .
      - key: OUTPUT_DIR
        value: ./transcripts
      - key: WHISPER_MODEL
        value: tiny
      - key: LANGUAGE
        value: vi
      - key: ALLOWED_ORIGINS
        value: https://frontend-jet-theta-nvf68h8ewg.vercel.app
      - key: MAX_UPLOAD_SIZE
        value: "524288000"
    plan: free
