CORRECTIONS = {
    r"mô đô|mô hình đô": "model",
    r"phai tu[aâ]n|phai t[uú]n|phai tunnel|fine-tunenel|fine-tuning[a-z]+": "fine-tuning",
    r"weights\s+tuning|file/weights tuning": "fine-tuning",
    r"Google Collapse|[Gg]roup [Cc]ollapse": "Google Colab",
    r"[Cc]hatchivity|[Cc]hat [Gg][Bb][Tt]|chát GBT|GBT\s*[0-9Oo]+": "ChatGPT",
    r"Stubborn Diffusion": "Stable Diffusion",
    r"tập fight|fight\b": "weights",
    r"cốt\b": "code",
    r"tiếng xế": "tiến sĩ",
    r"[Ss]oran\b": "Sora",
    r"LTI Modo|NGTI": "LLM",
    r"(\d+)\s*ghi\b": r"\1GB",
    r"[Gg]enu[ia]ty AI|[Gg]enitive AI|[Gg]enuity AI|[Gg]enity AI": "Generative AI",
    r"[Gg]enetic [Ee]ye [Mm]odel": "Generative AI Model",
    r"model [Gg]ov\b": "Transformer model (GPT)",
    r"mấy chân mê": "vài trăm MB",
    r"hàng ngàn ghi\s*gai": "hàng ngàn GB",
    r"viên mạng mở mở|viên mạng mở": "open source",
    r"mãi nguồn mỡ|mãi nguồn mở": "mã nguồn mở",
    r"kênh sao toán": "consultant/tư vấn",
    r"SQU-U|lũa Lung [Gg]ông": "UTS/Western Sydney",
    r"mất cưới": "mỗi",
    r"có sảnh": "có sẵn",
    r"binh hỏa": "viết/chạy",
    r"trụi hiểu": "chủ yếu",
    r"đội dụng": "nội dung",
    r"sửa lấy": "tạo ra",
    r"trang hạn": "chẳng hạn",
    r"giữ liệu": "dữ liệu",
    r"lưu tí\b": "gọi là",
    r"hành nhiên": "đương nhiên",
    r"mất tối thiệu|mẫu tối thiệu": "mức tối thiểu",
    r"tối thiệu": "tối thiểu",
    r"phai mẫu|phai target": "file target/mẫu",
    r"học chí": "thậm chí",
    r"phản viện": "phân biệt",
    r"xin ra": "sinh ra/tạo ra",
    r"một mồm": "nhóm nghiên cứu",
    r"túm hình": "tấm hình",
    r"chăm ảnh": "giống ảnh",
    r"cải biên": "cải tiến",
    r"[Cc]irculatex|[Cc]irculate[xk]": "ElevenLabs",
    r"[Mm]e [Aa]nyone|[Mm]eanyone": "HeyGen/MeAnyone",
    r"[Hh]ey[- ][Gg]en\b": "HeyGen",
    r"[Mm]id[- ][Jj]ourney|[Mm]idyourney": "Midjourney",
    r"[Rr]unaway\b|[Rr]un[- ][Ww]ay\b": "Runway",
    r"[Pp]ika [Ll]abs?": "Pika Labs",
    r"[Ll]uma [Aa][Ii]|[Ll]ooma": "Luma AI",
    r"[Kk]ling [Aa][Ii]": "Kling AI",
    r"[Cc]omfy[- ][Uu][Ii]|[Cc]omfyui": "ComfyUI",
    r"[Cc]o-?[Pp]ilot\b": "Copilot",
    r"cái thức\b": "kích thước",
    r"\bVIE\b": "VAE",
}
